### ISSUE TITLE
resourcePath incorrect when instantiating FMI3.0 FMUs

### ISSUE THREAD

**Issue by YonVanom** [jondo2010/rust-fmi#52]
When attempting to instantiate an FMI3.0 FMU using rust-fmi, _resourcePath_ is a URI, _i.e., starting with file://...,_ but for FMI3, this should be a path, _e.g., starting with C:\...,_ according to the standard. (This has changed between version 2 and 3 of the standard, as also indicated by the argument being renamed from _fmuResourceLocation_ to _resourcePath_).

- [Version 3.0](https://fmi-standard.org/docs/3.0.1/#resourcePath):
_resourcePath_ is **the absolute file path** (with a trailing file separator) of the resources directory of the extracted FMU archive.
[**Example**: An FMU is extracted to the directory C:\temp\MyFMU, then resourcePath = C:\temp\MyFMU\resources\.]

- [Version 2.0](https://github.com/modelica/fmi-standard/releases/download/v2.0.4/FMI-Specification-2.0.4.pdf) (p. 20):
Argument _fmuResourceLocation_ is **a URI** according to the IETF RFC3986 syntax to
indicate the location to the “resources” directory of the unzipped FMU archive. The
following schemes must be understood by the FMU:
Mandatory: “file” with absolute path (either including or omitting the authority component)
• Optional: “http”, “https”, “ftp”
• Reserved: “fmi2” for FMI for PLM.
[**Example**: An FMU is unzipped in directory “C:\temp\MyFMU”, then
fmuResourceLocation = “file:///C:/temp/MyFMU/resources” or
“file:/C:/temp/MyFMU/resources”. Function fmi2Instantiate is then able to read all
needed resources from this directory, for example maps or tables used by the FMU.]

**Comment by jondo2010** [comment]
@YonVanom thanks for the detailed report. This should now be fixed!
