### ISSUE TITLE
Add missing licenses to FMI headers and Reference FMUs

### ISSUE THREAD

**Issue by t-sommer** [jondo2010/rust-fmi#61]
This repository contains copies of the FMI headers and parts of the Reference FMUs licensed under the BSD 2-clause license without mentioning them in the "License" section of the readme and the license files.

**Comment by jondo2010** [comment]
Hi, thanks for the issue report. Can you clarify the request? The c header files, for example `fmi-sys/src/fmi2/hdrs/fmi2FunctionTypes.h`, contain the unmodified copyright and license notices. The reference FMUs are not stored directly in the repository, but rather are downloaded at runtime from the modelica org github releases.

**Comment by t-sommer** [comment]
The section "License" in the readme suggests that the contents of this repository are licensed under the Apache or MIT license which is not the case because it contains copied and derived work. I suggest that you either explicitly mention these resources in the "License" section and add the respective license files or include the original repositories as submodules.
